/*
	
	---- Revenue Analysis ---
	Total revenue generated by each city।
	Revenue generated by each vehicle type।
	Monthly revenue trend।
	Daily revenue trend।
	Revenue contribution (%) by city।
	Revenue contribution (%) by vehicle type।
	Top 20 revenue-generating days।
	Average income per driver।
	Average fare per trip by city।
	Highest surge revenue days।


*/


/*
1. Total revenue generated by each city.

Business Insight:
Shows which cities generate the highest total driver revenue.
Useful for market expansion and city-wise performance analysis.
*/

select 
	d.city,
	sum(total_income) as total_revenue
from drivers as d
join earnings as e
on d.driver_id = e.driver_id
group by d.city
order by total_revenue desc

/*
2. Revenue generated by each vehicle type
Business Insight:
Identifies which vehicle category contributes the most revenue.
Useful for fleet planning and incentive allocation.

*/

select 
	v.vehicle_id,
	sum(e.total_income) as total_revenue
from drivers as d
join vehicles as v
on d.vehicle_id = v.vehicle_id
join earnings as e
on e.driver_id = e.driver_id
group by v.vehicle_id
order by total_revenue desc





/*
3. Monthly revenue trend.

Business Insight:
Tracks monthly revenue growth and seasonal demand.

*/

select
	date_trunc('month', earning_date) as month,
	sum(total_income) as total_revenue
from earnings
group by month
order by month


/*
with cte as (
select 
	to_char(e.earning_date,'month') as month,
	sum(e.total_income) as total_revenue
from drivers as d
join earnings as e
on d.driver_id = e.driver_id
group by to_char(e.earning_date,'month')
)
select
	month,
	total_revenue,
	sum(total_revenue) over(order by month) as revenue_trend
from cte
*/




/*

4. Daily revenue trend
Business Insight:
Shows daily revenue fluctuations.
Useful for identifying high-demand days.
*/


select
	earning_date,
	sum(total_income) as total_revenue
from earnings
group by earning_date
order by earning_date

/*
5. Revenue contribution (%) by city.
Business Insight:
Measures each city's contribution to total revenue.
*/



with cte as (
select 
	d.city as city,
	sum(total_income) as total_revenue
	--round(sum(total_income)*100.0/sum(sum(total_income)) over(),2) as rc
from drivers as d
join earnings as e
on d.driver_id = e.driver_id
group by d.city
order by total_revenue desc
)

select
	city,
	total_revenue,
	round(total_revenue * 100.0/ sum(total_revenue) over(),2) as revenue_contribution
from cte
group by city,total_revenue
order by revenue_contribution desc




/*
6. Revenue contribution (%) by vehicle type
Business Insight:
Shows how much each vehicle type contributes to overall revenue.
*/



select 
	v.vehicle_type as vehicles,
	sum(e.total_income) as total_revenue,
	round(sum(e.total_income)*100.0 /
	(select sum(total_income) from earnings),2) as revenue_percentage
from earnings as e
join drivers as d
on e.driver_id = d.driver_id
join vehicles as v
on d.vehicle_id = v.vehicle_id
group by vehicles
order by revenue_percentage desc



/*

7. Top 20 revenue-generating days
Business Insight:
Identifies the highest revenue days for business planning.

*/


select
	earning_date,
	sum(total_income) as total_revenue
from earnings
group by earning_date
order by total_revenue desc
limit 20



/*
8. Average income per driver

*/

select 
	d.driver_id,
	d.full_name,
	round(avg(total_income),2) as avg_income
from drivers as d
join earnings as e
on d.driver_id = e.driver_id
group by d.full_name, d.driver_id
order by avg_income desc


/*
9. Average fare per trip by city
Business Insight:
Compares average trip fare across cities.
Useful for pricing strategy.
*/


select
	d.city,
	round(avg(t.fare),2) as avg_fare
from drivers as d
join trips as t
on d.driver_id = t.driver_id
where t.completed = true
group by d.city


/*
10. Highest surge revenue days
*/


select
	trip_date,
	round(sum(fare),2) as surge_revenue
from trips
where completed = true and surge_multiplier > 1
group by trip_date
order by surge_revenue desc
limit 20



	